version: "3.9"
services:
  db:
    image: mysql:8.2.0
    platform: linux/x86_64
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "4306:3306"
    security_opt:
      - seccomp:unconfined
